/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ayqvgrxdtjkgltajfjen"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5cXZncnhkdGprZ2x0YWpmamVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNzM2NTUsImV4cCI6MjA3NDk0OTY1NX0.nHI2aIt4kWIkOoZVgVdJ4MitPd-nnN-yJSUlkjETA20"